// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwitterDB.Context;

namespace MySql.Migrations.Migrations
{
    [DbContext(typeof(TwitterContext))]
    [Migration("20211130114543_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("TwitterCore.Models.Admin", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TwitterCore.Models.Agenda", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AgendaDetail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("TwitterCore.Models.Follow", b =>
                {
                    b.Property<Guid>("FollowerUserID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FollowingUserID")
                        .HasColumnType("char(36)");

                    b.HasKey("FollowerUserID", "FollowingUserID");

                    b.HasIndex("FollowingUserID");

                    b.ToTable("Follows");
                });

            modelBuilder.Entity("TwitterCore.Models.HashTag", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("AgendaID")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashTagDetail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TweetCounter")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AgendaID");

                    b.ToTable("HashTags");
                });

            modelBuilder.Entity("TwitterCore.Models.Like", b =>
                {
                    b.Property<Guid>("TweetID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("TweetID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("TwitterCore.Models.Retweet", b =>
                {
                    b.Property<Guid>("TweetID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("TweetID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("Retweet");
                });

            modelBuilder.Entity("TwitterCore.Models.Topic", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("TopicCategoryID")
                        .HasColumnType("char(36)");

                    b.Property<string>("TopicDetail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("TopicCategoryID");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("TwitterCore.Models.TopicCategory", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("TopicCategories");
                });

            modelBuilder.Entity("TwitterCore.Models.Tweet", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LikeCounter")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReplyCounter")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReplyMainTweetID")
                        .HasColumnType("char(36)");

                    b.Property<int>("ReplyStatus")
                        .HasColumnType("int");

                    b.Property<int>("RetweetCounter")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TopicID")
                        .HasColumnType("char(36)");

                    b.Property<string>("TweetDetail")
                        .HasMaxLength(280)
                        .HasColumnType("varchar(280)");

                    b.Property<Guid>("UserID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("ReplyMainTweetID");

                    b.HasIndex("TopicID");

                    b.HasIndex("UserID");

                    b.ToTable("Tweets");
                });

            modelBuilder.Entity("TwitterCore.Models.TweetHashTag", b =>
                {
                    b.Property<Guid>("TweetID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("HashTagID")
                        .HasColumnType("char(36)");

                    b.HasKey("TweetID", "HashTagID");

                    b.HasIndex("HashTagID");

                    b.ToTable("TweetsAndHashTags");
                });

            modelBuilder.Entity("TwitterCore.Models.TweetImage", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<Guid>("TweetID")
                        .HasColumnType("char(36)");

                    b.HasKey("ID");

                    b.HasIndex("TweetID");

                    b.ToTable("TweetImages");
                });

            modelBuilder.Entity("TwitterCore.Models.TweetMention", b =>
                {
                    b.Property<Guid>("TweetID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MentionedUserID")
                        .HasColumnType("char(36)");

                    b.HasKey("TweetID", "MentionedUserID");

                    b.ToTable("TweetsAndMentions");
                });

            modelBuilder.Entity("TwitterCore.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BackgroundPath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FollowerCounter")
                        .HasColumnType("int");

                    b.Property<int>("FollowingCounter")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("PersonalInfo")
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<string>("PersonalWebSiteURL")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePicPath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TwitterCore.Models.Follow", b =>
                {
                    b.HasOne("TwitterCore.Models.User", "FollowerUser")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TwitterCore.Models.User", "FollowingUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingUserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FollowerUser");

                    b.Navigation("FollowingUser");
                });

            modelBuilder.Entity("TwitterCore.Models.HashTag", b =>
                {
                    b.HasOne("TwitterCore.Models.Agenda", "Agenda")
                        .WithMany("HashTags")
                        .HasForeignKey("AgendaID");

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("TwitterCore.Models.Like", b =>
                {
                    b.HasOne("TwitterCore.Models.Tweet", "Tweet")
                        .WithMany("UsersWhoLiked")
                        .HasForeignKey("TweetID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TwitterCore.Models.User", "User")
                        .WithMany("LikedTweets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tweet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitterCore.Models.Retweet", b =>
                {
                    b.HasOne("TwitterCore.Models.Tweet", "Tweet")
                        .WithMany("Retweets")
                        .HasForeignKey("TweetID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TwitterCore.Models.User", "User")
                        .WithMany("Retweets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tweet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitterCore.Models.Topic", b =>
                {
                    b.HasOne("TwitterCore.Models.TopicCategory", "TopicCategory")
                        .WithMany("Topics")
                        .HasForeignKey("TopicCategoryID");

                    b.Navigation("TopicCategory");
                });

            modelBuilder.Entity("TwitterCore.Models.Tweet", b =>
                {
                    b.HasOne("TwitterCore.Models.Tweet", "ReplyMainTweet")
                        .WithMany("ReplyTweets")
                        .HasForeignKey("ReplyMainTweetID");

                    b.HasOne("TwitterCore.Models.Topic", "Topic")
                        .WithMany("Tweets")
                        .HasForeignKey("TopicID");

                    b.HasOne("TwitterCore.Models.User", "User")
                        .WithMany("Tweets")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReplyMainTweet");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitterCore.Models.TweetHashTag", b =>
                {
                    b.HasOne("TwitterCore.Models.HashTag", "HashTag")
                        .WithMany("TweetsOfHashtag")
                        .HasForeignKey("HashTagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitterCore.Models.Tweet", "Tweet")
                        .WithMany("HashtagsOfTweet")
                        .HasForeignKey("TweetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HashTag");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("TwitterCore.Models.TweetImage", b =>
                {
                    b.HasOne("TwitterCore.Models.Tweet", "Tweet")
                        .WithMany("ImagesOfTweet")
                        .HasForeignKey("TweetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("TwitterCore.Models.TweetMention", b =>
                {
                    b.HasOne("TwitterCore.Models.Tweet", "Tweet")
                        .WithMany("Mentions")
                        .HasForeignKey("TweetID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TwitterCore.Models.User", "MentionedUser")
                        .WithMany("MentionedTweets")
                        .HasForeignKey("TweetID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MentionedUser");

                    b.Navigation("Tweet");
                });

            modelBuilder.Entity("TwitterCore.Models.Agenda", b =>
                {
                    b.Navigation("HashTags");
                });

            modelBuilder.Entity("TwitterCore.Models.HashTag", b =>
                {
                    b.Navigation("TweetsOfHashtag");
                });

            modelBuilder.Entity("TwitterCore.Models.Topic", b =>
                {
                    b.Navigation("Tweets");
                });

            modelBuilder.Entity("TwitterCore.Models.TopicCategory", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("TwitterCore.Models.Tweet", b =>
                {
                    b.Navigation("HashtagsOfTweet");

                    b.Navigation("ImagesOfTweet");

                    b.Navigation("Mentions");

                    b.Navigation("ReplyTweets");

                    b.Navigation("Retweets");

                    b.Navigation("UsersWhoLiked");
                });

            modelBuilder.Entity("TwitterCore.Models.User", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("LikedTweets");

                    b.Navigation("MentionedTweets");

                    b.Navigation("Retweets");

                    b.Navigation("Tweets");
                });
#pragma warning restore 612, 618
        }
    }
}
